spring.application.name=GameCore

#Conexion MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/gamecore_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Clave
jwt.secret=${JWT_SECRET:clave-secreta-gamecore-2026-segura-jwt-XkZ9mP2qL7vN4wR8}
jwt.expiration=${JWT_EXPIRATION:36000000}

